apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-claim
  labels:
    app: mongo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
