apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: reach-systems/main-ui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: ui-config
        env:
        - name: API_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: ui-config
              key: api_url
        